name: unity-catalog
description: Lakehouse - Unity Catalog Configuration
backend: terraform

# List of Resources to deploy
resources:

  # Groups
  databricks_groups: ${include.resources/groups.yaml}

  # Users
  databricks_users: ${include.resources/users.yaml}

  # Service Principals
  databricks_serviceprincipals: ${include.resources/serviceprincipals.yaml}

  # Metastore
  databricks_metastores:
    metastore-demo: ${include.resources/metastore.yaml}

  # External locations
  databricks_externallocations: ${include.resources/externallocations.yaml}

  # Catalogs
  databricks_catalogs: ${include.resources/catalogs.yaml}

  # Databricks Providers Configuration
  providers:

    # Account Provider
    # The account-level provider configuration varies by cloud provider.
    # For more details, visit
    # https://docs.databricks.com/en/dev-tools/auth/oauth-m2m.html
    databricks:
      host: https://accounts.azuredatabricks.net
      account_id: ${vars.DATABRICKS_ACCOUNT_ID}
      azure_tenant_id: ${vars.AZURE_TENANT_ID}
      azure_client_id: ${vars.AZURE_CLIENT_ID}
      azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
      auth_type: azure-client-secret

    # Workspace Providers
    # Required for the deployment of catalogs to bind a catalog to a specific
    # workspace, even if catalogs may be shared across all workspaces.
    databricks.dev:
      alias: dev
      host: ${vars.DATABRICKS_HOST_DEV}
      token: ${vars.DATABRICKS_TOKEN_DEV}

variables:
  workspace_id_dev: 895281958259747
  landing_storage_location_dev: abfss://landing@o3stglakehousedev.dfs.core.windows.net/
  landing_storage_location_prd: abfss://landing@o3stglakehouseprd.dfs.core.windows.net/